name: Create Release with Version Validation

on:
  pull_request:
    branches:
      - main
    types:
      - closed  # Trigger when the PR is merged into the main branch

jobs:
  validate_version:
    uses: ./.github/workflows/version-validation.yml  # Reuse the version validation workflow
    with:
      branch_name: ${{ github.event.pull_request.head.ref }}

  create_release:
    needs: validate_version
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract version from branch name
        id: extract_version
        run : |
          VERSION=$(echo "${{ github.event.pull_request.head.ref }}" | sed -n 's|.*/\(v.*\)|\1|p')
          echo "Extracted Release Branch Version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        # run: |
        #   VERSION=$(echo "${{ github.event.head_commit.message }}" | grep -o 'release/v[0-9]\+\.[0-9]\+\.[0-9]\+' | sed 's/release\///')
        #   echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up Git for push access
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      
      - name: Create Release Tag
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Use the PAT from repository secrets
        run: |
          git tag "v${{ env.VERSION }}"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }} --tags

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} 
        uses: actions/create-release@v1
        with:
          tag_name: "v${{ env.VERSION }}"
          release_name: "Release v${{ env.VERSION }}"
          draft: false
          prerelease: false