name: Production Deployment

# Trigger the workflow when a release is created (with a version tag)
on:
  release:
    types: [published]  # When a release is published

jobs:
  deploy_production:
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: https://githubaction-test-prod.com
    permissions:
      contents: write  # Need write permissions to deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (example)
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Deploy to Production
        run: echo "Deploying version ${{ github.event.release.tag_name }} to production..."  # Replace with actual deployment command

      - name: Notify Success
        run: echo "Production deployment for version ${{ github.event.release.tag_name }} was successful!"