name: Version Validation

on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string

jobs:
  validate_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all commits and tags

      - name: Validate branch name format
        id: validate_branch
        run: |
          BRANCH_NAME="${{ inputs.branch_name }}"
          echo "${{ inputs.branch_name }}"
          if [[ ! $BRANCH_NAME =~ ^release/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Branch name does not match semantic versioning pattern (release/vX.Y.Z)."
            exit 1
          fi
          VERSION=$(echo $BRANCH_NAME | sed 's/release\///')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Compare with latest tag
        run: |
          # Check if there are any tags
          if git describe --tags `git rev-list --tags --max-count=1` > /dev/null 2>&1; then
            LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
            echo "Latest tag found: $LATEST_TAG"
            
            # Compare extracted version with the latest tag
            if [[ "$(printf '%s\n' "$LATEST_TAG" "${{ env.VERSION }}" | sort -V | head -n1)" != "$LATEST_TAG" ]]; then
              echo "Error: Version ${{ env.VERSION }} is not newer than the latest tag $LATEST_TAG."
              exit 1
            else
              echo "Proceeding with version ${{ env.VERSION }} which is newer than the latest tag $LATEST_TAG."
            fi
          else
            echo "No previous tags found, proceeding with version ${{ env.VERSION }}."
          fi